### ISSUE TITLE
Update LICENSE.md

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/stretch#10]
1. Remove from README (duplicative).
2. Figure out how to properly credit both Stretch2 contributors and original Visly team.

**Comment by mockersf** [comment]
https://github.com/vislyhq/stretch/pull/85 should also be merged in this repo so that crates.io can correctly display the license

**Comment by TimJentzsch** [comment]
Stretch is licensed under MIT while bevy is dual-licensed with Apache as well. Is this going to cause issues?

**Comment by alice-i-cecile** [comment]
It won't cause issues; we can just leave this as a separate repo under just MIT.

**Comment by NickAcPT** [comment]
> 2. Figure out how to properly credit both Stretch2 contributors and original Visly team.

Regarding this, I think the best action would be to add an extra line of copyright like explained in [this](https://opensource.stackexchange.com/a/6730) Stack Exchange answer.

So for this repo, adding something like the following below the existing Copyright line might be enough:
```
Copyright (c) 2022 Dioxus
```

**Comment by alice-i-cecile** [comment]
> Copyright (c) 2022 Dioxus

I would change this to `Stretch2 contributors` (or whatever name we end up on), but otherwise this sounds great to me.
