### ISSUE TITLE
Add mdlint to CI

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/stretch#13]
We have a bit of markdown now, and the amount will increase over time.

This is helpful to avoid frustrating formatting diffs and surprising rendering.

**Comment by TimJentzsch** [comment]
I assume we can/should use bevy as a reference here?

https://github.com/bevyengine/bevy/blob/main/.github/workflows/ci.yml#L184-L198

**Comment by TimJentzsch** [comment]
Notably, bevy seems to have an additional [`check-markdown-links` step](https://github.com/bevyengine/bevy/blob/ae580e58dd1d8539e26a44a4d428e1aa45a3d6f9/.github/workflows/ci.yml#L202-L249) and some additional configuration in the [`.github/linters`](https://github.com/bevyengine/bevy/tree/main/.github/linters) folder, maybe that's relevant here as well.

**Comment by alice-i-cecile** [comment]
> I assume we can/should use bevy's CI as a reference here?

Yep, I've been happy with the setup we have there.

> Notably, bevy seems to have an additional check-markdown-links step and some additional configuration in the [.github/linters](https://github.com/bevyengine/bevy/tree/main/.github/linters) folder, maybe that's relevant here as well.

check-markdown-links is frustratingly flaky; skip it here. https://github.com/bevyengine/bevy/blob/main/.github/linters/.markdown-lint.yml can be useful, but it's only used to define / configure rules. Include it as an empty file to start, and then we can add more rules as needed.
