### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/stretch#16]
This can and should be very simple to start.

Previous text:

## Contributing
Contributions are very welcome. Though we ask that you open an issue or pull request early in the process (before writing code) so we can discuss solutions and additions before you start spending time on implementing them. There are some specific areas where we would be extra happy to receive contributions in.

- Binary size reduction
- Runtime performance
- Ensure build / test environment works well on non macOS platforms
- Alternate layout systems (grid layout perhaps?)
- Web compatibility tests
- RTL support
- Platform bindings
- API improvements
- Documentation & Examples

**Comment by asur4s** [comment]
> Should you wish to work on an issue, please claim it first by commenting on the GitHub issue that you want to work on it. This is to prevent duplicated efforts from contributors on the same issue.

I think it is necessary to add this sentence.  You can assign it to me.

**Comment by TimJentzsch** [comment]
This is also related to #15.
