### ISSUE TITLE
Add #![forbid(unsafe_code)] crate-level rule

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/stretch#21]
Currently, there's no use of unsafe code, and we should keep it that way.

**Comment by TimJentzsch** [comment]
There are two usages of the `unsafe` keyword:

- https://github.com/DioxusLabs/stretch/blob/c267e6296caea4217a498935ccaf57483b5c9235/src/forest.rs#L160-L163
- https://github.com/DioxusLabs/stretch/blob/c267e6296caea4217a498935ccaf57483b5c9235/src/node.rs#L156

But it looks like this is both for the same function which is marked as `unsafe`, but doesn't use an actual `unsafe` block.

How should these be handled?

**Comment by alice-i-cecile** [comment]
It looks like both of those can just be made safe? That's bizarre.

**Comment by TimJentzsch** [comment]
I agree that it should be removed. Are you enable to infer what about this function is "unsafe"? Then I will remove the `unsafe` keywords and move it to the docs.

**Comment by alice-i-cecile** [comment]
I'm not sure, it's not any more risky than `remove_child_at_index`. Perhaps hierarchy desynchronization concerns?

I actually expect that this is legacy `unsafe` annotations: they may have been using interior mutability in a sloppy way that has since been removed. Let me check the commit history of the file.
