### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/stretch#29]
The bug template here is particularly useful: https://github.com/bevyengine/bevy/pull/4652

I would also probably grab the Enhancement issue template from Bevy.

**Comment by asur4s** [comment]
Is it better to use yaml file format?

**Comment by alice-i-cecile** [comment]
I have no strong feelings there. I genuinely don't know if there's a feature gap between the different formats for issue templates.
