### ISSUE TITLE
Add a RELEASES.md file

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/stretch#31]
This should be updated as part of each PR, see #30.

Feel free to steal the structure from https://github.com/Leafwing-Studios/leafwing_input_manager/blob/main/RELEASES.md

**Comment by TimJentzsch** [comment]
Should this PR just add a more or less empty file with the `# Release Notes` header, or do we already have changes to report?

**Comment by alice-i-cecile** [comment]
There are already some changes to report :) Check the commit history for the changes that have been made since we diverged from `stretch`.
